### ISSUE TITLE
plugins section

### ISSUE THREAD

**Issue by masihfathi** [andris9/zonemta-delivery-counters#1]
Where we should add this part:

...
  "plugins": {
    "modules/zonemta-delivery-counters": {
      "enabled": "main",
      "redis": "redis://localhost:6379/2",
      "prefix": "zmta"
    }
  }
...

In : /opt/zone-mta/config/default.js path?

**Comment by YosuCadilla** [comment]
I get: No such file or directory

**Comment by andris9** [comment]
@YosuCadilla see [zone-mta-template](https://github.com/zone-eu/zone-mta-template) as it has zonemta-delivery-counters enabled by default

**Comment by YosuCadilla** [comment]
Thank you @andris9 !
I would gladly help improving documentation if you allow me.

**Comment by YosuCadilla** [comment]
In this particular case MY problem was that the instructions found here:
https://github.com/zone-eu/zmta-webadmin
State that I needed to install this plugin (a mention of the plugin being already installed by default when running the standard installation would save people some confusion).

Those kind of issues can be very frustrating and give the impression (to newcomers like me) that zone-mta is not well tested. It would also save you time responding to stupid issues like mine :-) in the future...

**Comment by andris9** [comment]
@YosuCadilla yeah, sorry about that, ZoneMTA is tested and built internally, so public documentation might be outdated or missing. If you want to help regarding documentation, then make a pull request against README or edit project Wikis in Github (if wiki is not publicly editable, then let me know)

**Comment by YosuCadilla** [comment]
OK, I will.
Let me make sure I got a working installation first, otherwise whatever I contribute might be wrong...
